SELECT 
      'private '||
      DECODE( DATA_TYPE , 'NUMBER', 'int ', 'String ' )||
      LOWER(COLUMN_NAME)||';'
 FROM COLS
WHERE TABLE_NAME = 'RESTR'
ORDER BY COLUMN_ID;

INSERT INTO RESTR
VALUES ((SELECT NVL(MAX(RESTR_NO),0)+1 FROM RESTR;), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? );

SELECT NVL(MAX(RESTR_NO),0)+1 FROM RESTR;

SELECT
      'param.add(restrVo.get'||SUBSTR(COLUMN_NAME,0,1)||
      LOWER(SUBSTR(COLUMN_NAME,1))||'());'
  FROM COLS
 WHERE TABLE_NAME = 'RESTR'
 ORDER BY COLUMN_ID;
 
 
 SELECT B.*
 FROM
( SELECT ROWNUM RN, A.*
  FROM
    (SELECT *
     FROM RESTR
      ORDER BY RESTR_NO) A) B
WHERE RN>=1 AND RN<=10;


WITH B AS (
SELECT ROWNUM RN, A.*
  FROM
    (SELECT *
     FROM RESTR
      ORDER BY RESTR_NO) A
)
SELECT *
FROM B
WHERE RN>=11 AND RN<=20;