--C
 INSERT INTO JAVA_BOARD(NO,TITLE,CONTENT,WRITER)
 VALUES ((SELECT NVL(MAX(NO),0)+1 FROM JAVA_BOARD
 
---R (LIST)
 SELECT NO,
        TITLE,
        SUBSTR(CONTENT,0,10) AS CONTENT,
        WRITER 
   FROM JAVA_BOARD
  WHERE DLEYN = 'N'
  ORDER BY NO DESC;
  
---R (DETAIL)
 SELECT NO,
        TITLE,
        CONTENT,
        WRITER 
   FROM JAVA_BOARD
  WHERE NO=1; 
  
---U ()
 UPDATE JAVA_BOARD
    SET TITLE='-',
        CONTENT='-',
        WRITER='-'
  WHERE NO=1;

--커밋전 자료찾기(10분)
 SELECT *
   FROM JAVA_BOARD AS OF
   TIMESTAMP(SYSTIMESTAMP - INTERVAL '10' MINUTE)

---D
 UPDATE JAVA_BOARD
    SET DLEYN='Y'
  WHERE NO=1;  
  
  INSERT INTO JAVA_BOARD
         SELECT NO+(SELECT MAX(NO) FROM JAVA_BOARD), 
                TITLE||ROWNUM, CONTENT, WRITER, DLEYN
           FROM JAVA_BOARD;

 
  
 

