-- 자바의 정석 (BOOK_NO = 101)
INSERT INTO REAL_BOOKS (REAL_BOOK, REAL_BOOK_STATUS, BOOK_NO) VALUES (1001, '대출가능', 101);
INSERT INTO REAL_BOOKS (REAL_BOOK, REAL_BOOK_STATUS, BOOK_NO) VALUES (1002, '대출가능', 101);
INSERT INTO REAL_BOOKS (REAL_BOOK, REAL_BOOK_STATUS, BOOK_NO) VALUES (1003, '대출가능', 101);

-- SQL 첫걸음 (BOOK_NO = 102)
INSERT INTO REAL_BOOKS (REAL_BOOK, REAL_BOOK_STATUS, BOOK_NO) VALUES (1004, '대출가능', 102);
INSERT INTO REAL_BOOKS (REAL_BOOK, REAL_BOOK_STATUS, BOOK_NO) VALUES (1005, '대출가능', 102);
INSERT INTO REAL_BOOKS (REAL_BOOK, REAL_BOOK_STATUS, BOOK_NO) VALUES (1006, '대출가능', 102);

-- HTML&CSS 디자인 교과서 (BOOK_NO = 103)
INSERT INTO REAL_BOOKS (REAL_BOOK, REAL_BOOK_STATUS, BOOK_NO) VALUES (1007, '대출가능', 103);
INSERT INTO REAL_BOOKS (REAL_BOOK, REAL_BOOK_STATUS, BOOK_NO) VALUES (1008, '대출가능', 103);
INSERT INTO REAL_BOOKS (REAL_BOOK, REAL_BOOK_STATUS, BOOK_NO) VALUES (1009, '대출가능', 103);

-- 이펙티브 자바 (BOOK_NO = 104)
INSERT INTO REAL_BOOKS (REAL_BOOK, REAL_BOOK_STATUS, BOOK_NO) VALUES (1010, '대출가능', 104);
INSERT INTO REAL_BOOKS (REAL_BOOK, REAL_BOOK_STATUS, BOOK_NO) VALUES (1011, '대출가능', 104);
INSERT INTO REAL_BOOKS (REAL_BOOK, REAL_BOOK_STATUS, BOOK_NO) VALUES (1012, '대출가능', 104);

-- 모던 자바스크립트 (BOOK_NO = 105)
INSERT INTO REAL_BOOKS (REAL_BOOK, REAL_BOOK_STATUS, BOOK_NO) VALUES (1013, '대출가능', 105);
INSERT INTO REAL_BOOKS (REAL_BOOK, REAL_BOOK_STATUS, BOOK_NO) VALUES (1014, '대출가능', 105);
INSERT INTO REAL_BOOKS (REAL_BOOK, REAL_BOOK_STATUS, BOOK_NO) VALUES (1015, '대출가능', 105);

-- 스프링 부트 인 액션 (BOOK_NO = 106)
INSERT INTO REAL_BOOKS (REAL_BOOK, REAL_BOOK_STATUS, BOOK_NO) VALUES (1016, '대출가능', 106);
INSERT INTO REAL_BOOKS (REAL_BOOK, REAL_BOOK_STATUS, BOOK_NO) VALUES (1017, '대출가능', 106);
INSERT INTO REAL_BOOKS (REAL_BOOK, REAL_BOOK_STATUS, BOOK_NO) VALUES (1018, '대출가능', 106);

-- 자바자바 (BOOK_NO = 107)
INSERT INTO REAL_BOOKS (REAL_BOOK, REAL_BOOK_STATUS, BOOK_NO) VALUES (1019, '대출가능', 107);
INSERT INTO REAL_BOOKS (REAL_BOOK, REAL_BOOK_STATUS, BOOK_NO) VALUES (1020, '대출가능', 107);
INSERT INTO REAL_BOOKS (REAL_BOOK, REAL_BOOK_STATUS, BOOK_NO) VALUES (1021, '대출가능', 107);
