2025-0206-02)날짜자료
 - DATE(기본 날짜자료), TIMESTAMP, TIMESTAMP WITH LOCAL TIME ZONE,
   TIMESTAMP WITH TIME ZONE,
 - 날짜데이터는 덧셈(+)과 뺄셈(-)의 대상이 됨
사용형식)
 컬럼명 DATE
 컬럼명 TIMESTAMP
 컬럼명 TIMESTAMP WITH LOCAL TIME ZONE
 컬럼명 TIMESTAMP WITH TIME ZONE
 
사용예)
  CREATE TABLE TEMP05(
    COL1 DATE,
    COL2 DATE,
    COL3 DATE,
    COL4 TIMESTAMP,
    COL5 TIMESTAMP WITH LOCAL TIME ZONE,
    CLO6 TIMESTAMP WITH TIME ZONE
 );
 
  INSERT INTO TEMP05 VALUES(SYSDATE,SYSDATE-10,SYSDATE+10,
                     SYSTIMESTAMP,SYSTIMESTAMP,SYSTIMESTAMP);
  SELECT *FROM TEMP05;
  ALTER SESSION SET NLS_DATE_FORMAT ='YYYY/MM/DD HH24:MI:SS';
  
  SELECT TO_CHAR(COL1,'YYYY-MM-DD HH24:MI:SS')
    FROM TEMP05;