CREATE TABLE LOAN_STATS (
  MONTH_NO VARCHAR2(10),
  COUNT NUMBER
);

INSERT INTO LOAN_STATS VALUES ('1월', 12);
INSERT INTO LOAN_STATS VALUES ('2월', 19);
INSERT INTO LOAN_STATS VALUES ('3월', 3);
INSERT INTO LOAN_STATS VALUES ('4월', 5);
INSERT INTO LOAN_STATS VALUES ('5월', 2);
INSERT INTO LOAN_STATS VALUES ('6월', 10);
INSERT INTO LOAN_STATS VALUES ('7월', 6);
INSERT INTO LOAN_STATS VALUES ('8월', 10);
INSERT INTO LOAN_STATS VALUES ('9월', 18);
INSERT INTO LOAN_STATS VALUES ('10월', 21);


CREATE TABLE RETURN_SCHEDULE (
  MEMBER_NAME VARCHAR2(50),
  BOOK_TITLE VARCHAR2(100),
  RETURN_DATE DATE
);

INSERT INTO RETURN_SCHEDULE VALUES ('홍길동', '자바의 정석', TO_DATE('2025-04-20', 'YYYY-MM-DD'));
INSERT INTO RETURN_SCHEDULE VALUES ('김철수', 'SQL 첫걸음', TO_DATE('2025-04-22', 'YYYY-MM-DD'));

SELECT 
    'private ' || 
    DECODE(DATA_TYPE, 'NUMBER', 'int ', 'String ') || 
    LOWER(SUBSTR(REPLACE(INITCAP(REPLACE(LOWER(COLUMN_NAME), '_', ' ')), ' ', ''), 1, 1)) || 
    SUBSTR(REPLACE(INITCAP(REPLACE(LOWER(COLUMN_NAME), '_', ' ')), ' ', ''), 2) || 
    ';'
FROM COLS
WHERE TABLE_NAME = 'RETURN_SCHEDULE'
ORDER BY COLUMN_ID;
