CREATE TABLE HIGH_SCHOOL (
    HS_ID              NUMBER          NOT NULL, -- 고등학교ID
    HS_CODE            VARCHAR2(20)    NOT NULL, -- 학교코드
    HS_NAME            VARCHAR2(100)   NOT NULL, -- 학교명
    HS_REGION_CODE     VARCHAR2(6)     NOT NULL, -- 시도코드
    HS_JURIS_CODE      VARCHAR2(6)     NOT NULL, -- 관할교육청 코드
    HS_FOUND_TYPE      VARCHAR2(6),              -- 설립유형
    HS_ZIPCODE         VARCHAR2(10),             -- 우편번호
    HS_ADDR            VARCHAR2(200),            -- 기본주소
    HS_ADDR_DETAIL     VARCHAR2(200),            -- 상세주소
    HS_TEL             VARCHAR2(20),             -- 전화번호
    HS_HOMEPAGE        VARCHAR2(300),            -- 홈페이지URL
    HS_COEDU_TYPE      VARCHAR2(6),              -- 남녀공학 구분
    HS_TYPE_NAME       VARCHAR2(20),             -- 학교종류구분 (일반/특성화 등)
    HS_GENERAL_TYPE    VARCHAR2(6),              -- 일반계/전문계
    HS_FOUND_DATE      DATE,                     -- 설립일자
    HS_ANNIV_AT        DATE,                     -- 개교기념일
    HS_TOTAL_STUDENTS  NUMBER                    -- 전교생 수
);

-- PK 지정
ALTER TABLE HIGH_SCHOOL ADD CONSTRAINT PK_HIGH_SCHOOL PRIMARY KEY (HS_ID);

-- 코멘트 추가
COMMENT ON TABLE HIGH_SCHOOL IS '고등학교 기본정보';
COMMENT ON COLUMN HIGH_SCHOOL.HS_ID             IS '고등학교ID';
COMMENT ON COLUMN HIGH_SCHOOL.HS_CODE           IS '학교코드';
COMMENT ON COLUMN HIGH_SCHOOL.HS_NAME           IS '학교명';
COMMENT ON COLUMN HIGH_SCHOOL.HS_REGION_CODE    IS '시도코드';
COMMENT ON COLUMN HIGH_SCHOOL.HS_JURIS_CODE     IS '관할교육청 코드';
COMMENT ON COLUMN HIGH_SCHOOL.HS_FOUND_TYPE     IS '설립유형';
COMMENT ON COLUMN HIGH_SCHOOL.HS_ZIPCODE        IS '우편번호';
COMMENT ON COLUMN HIGH_SCHOOL.HS_ADDR           IS '기본주소';
COMMENT ON COLUMN HIGH_SCHOOL.HS_ADDR_DETAIL    IS '상세주소';
COMMENT ON COLUMN HIGH_SCHOOL.HS_TEL            IS '전화번호';
COMMENT ON COLUMN HIGH_SCHOOL.HS_HOMEPAGE       IS '홈페이지URL';
COMMENT ON COLUMN HIGH_SCHOOL.HS_COEDU_TYPE     IS '남녀공학 구분';
COMMENT ON COLUMN HIGH_SCHOOL.HS_TYPE_NAME      IS '학교종류구분';
COMMENT ON COLUMN HIGH_SCHOOL.HS_GENERAL_TYPE   IS '학교일반/전문계 구분';
COMMENT ON COLUMN HIGH_SCHOOL.HS_FOUND_DATE     IS '설립일자';
COMMENT ON COLUMN HIGH_SCHOOL.HS_ANNIV_AT       IS '개교기념일';
COMMENT ON COLUMN HIGH_SCHOOL.HS_TOTAL_STUDENTS IS '전교생 수';

------------------------------------------------------------

CREATE TABLE HIGH_SCHOOL_DEPT (
    HSD_ID          NUMBER         NOT NULL, -- 학과ID
    HS_ID           NUMBER         NOT NULL, -- 고등학교ID (FK)
    HSD_CODE        VARCHAR2(6),             -- 학교코드
    HSD_NAME        VARCHAR2(100) NOT NULL, -- 학과명
    HSD_TRACK_NAME  VARCHAR2(6)             -- 계열명
);

-- PK 지정
ALTER TABLE HIGH_SCHOOL_DEPT ADD CONSTRAINT PK_HIGH_SCHOOL_DEPT PRIMARY KEY (HSD_ID);

-- FK 지정
ALTER TABLE HIGH_SCHOOL_DEPT ADD CONSTRAINT FK_HIGH_SCHOOL_DEPT_HS
FOREIGN KEY (HS_ID) REFERENCES HIGH_SCHOOL(HS_ID);

-- 코멘트 추가
COMMENT ON TABLE HIGH_SCHOOL_DEPT IS '고등학교 학과 정보';
COMMENT ON COLUMN HIGH_SCHOOL_DEPT.HSD_ID         IS '학과ID';
COMMENT ON COLUMN HIGH_SCHOOL_DEPT.HS_ID          IS '고등학교ID';
COMMENT ON COLUMN HIGH_SCHOOL_DEPT.HSD_CODE       IS '학교코드';
COMMENT ON COLUMN HIGH_SCHOOL_DEPT.HSD_NAME       IS '학과명';
COMMENT ON COLUMN HIGH_SCHOOL_DEPT.HSD_TRACK_NAME IS '계열명 (예: 인문, 자연계)';


-----------------------------------------------

CREATE TABLE COM_CODE_CL (
    CL_ID        VARCHAR2(3)   NOT NULL, -- 분류코드
    CL_NAME      VARCHAR2(100) NOT NULL, -- 분류코드명
    CL_DESC      VARCHAR2(200),          -- 분류코드설명
    USE_YN       CHAR(1)       NOT NULL, -- 사용여부
    CREATED_AT   DATE,                   -- 최초생성일시
    CREATED_BY   VARCHAR2(50),           -- 최초생성자
    UPDATED_AT   DATE,                   -- 최종수정일시
    UPDATED_BY   VARCHAR2(50)            -- 최종수정자
);

ALTER TABLE COM_CODE_CL ADD CONSTRAINT PK_COM_CODE_CL PRIMARY KEY (CL_ID);

-- COMMENTS
COMMENT ON TABLE COM_CODE_CL IS '공통분류코드';
COMMENT ON COLUMN COM_CODE_CL.CL_ID       IS '분류코드';
COMMENT ON COLUMN COM_CODE_CL.CL_NAME     IS '분류코드명';
COMMENT ON COLUMN COM_CODE_CL.CL_DESC     IS '분류코드설명';
COMMENT ON COLUMN COM_CODE_CL.USE_YN      IS '사용여부';
COMMENT ON COLUMN COM_CODE_CL.CREATED_AT  IS '최초생성일시';
COMMENT ON COLUMN COM_CODE_CL.CREATED_BY  IS '최초생성자';
COMMENT ON COLUMN COM_CODE_CL.UPDATED_AT  IS '최종수정일시';
COMMENT ON COLUMN COM_CODE_CL.UPDATED_BY  IS '최종수정자';

----------------------------------------------------------------

CREATE TABLE COM_CODE (
    CC_ID        VARCHAR2(6)   NOT NULL, -- 공통상세코드
    CL_CODE      VARCHAR2(3)   NOT NULL, -- 분류코드
    CC_NAME      VARCHAR2(100) NOT NULL, -- 공통상세코드명
    CC_ETC       VARCHAR2(200),          -- 공통상세코드설명
    USE_YN       CHAR(1)       NOT NULL, -- 사용여부
    CREATED_AT   DATE DEFAULT SYSDATE,   -- 최초생성일시
    CREATED_BY   VARCHAR2(50),           -- 최초생성자
    UPDATED_AT   DATE DEFAULT SYSDATE,   -- 최종수정일시
    UPDATED_BY   VARCHAR2(50)            -- 최종수정자
);

ALTER TABLE COM_CODE ADD CONSTRAINT PK_COM_CODE PRIMARY KEY (CC_ID);

-- FK
ALTER TABLE COM_CODE
ADD CONSTRAINT FK_COM_CODE_CL
FOREIGN KEY (CL_CODE) REFERENCES COM_CODE_CL(CL_ID);

-- COMMENTS
COMMENT ON TABLE COM_CODE IS '공통코드';
COMMENT ON COLUMN COM_CODE.CC_ID        IS '공통상세코드';
COMMENT ON COLUMN COM_CODE.CL_CODE      IS '분류코드';
COMMENT ON COLUMN COM_CODE.CC_NAME      IS '공통상세코드명';
COMMENT ON COLUMN COM_CODE.CC_ETC       IS '공통상세코드설명';
COMMENT ON COLUMN COM_CODE.USE_YN       IS '사용여부';
COMMENT ON COLUMN COM_CODE.CREATED_AT   IS '최초생성일시';
COMMENT ON COLUMN COM_CODE.CREATED_BY   IS '최초생성자';
COMMENT ON COLUMN COM_CODE.UPDATED_AT   IS '최종수정일시';
COMMENT ON COLUMN COM_CODE.UPDATED_BY   IS '최종수정자';

---------------------------------------------------------
--공통분류코드 INSERT
INSERT INTO COM_CODE_CL (CL_ID, CL_NAME, CL_DESC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('G21', '설립유형', '국공사립 구분', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');

INSERT INTO COM_CODE_CL (CL_ID, CL_NAME, CL_DESC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('G22', '교육청코드', '시도교육청', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');

INSERT INTO COM_CODE_CL (CL_ID, CL_NAME, CL_DESC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('G23', '시도명코드', '지역명 코드', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');

INSERT INTO COM_CODE_CL (CL_ID, CL_NAME, CL_DESC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('G24', '남녀공학구분', '남, 여, 공학', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');

INSERT INTO COM_CODE_CL (CL_ID, CL_NAME, CL_DESC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('G25', '학교종류', '초, 중, 고', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');

INSERT INTO COM_CODE_CL (CL_ID, CL_NAME, CL_DESC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('G26', '학교일반실업계구분', '일반고/실업계 등', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');

INSERT INTO COM_CODE_CL (CL_ID, CL_NAME, CL_DESC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('G27', '학과코드', '고등학교 학과 코드 구분', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');

INSERT INTO COM_CODE_CL (CL_ID, CL_NAME, CL_DESC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('G31', '고등학교학과계열 ', '고등학교 학과 계열 구분', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');


-----------------------------------------------------------------------------
--공통코드 INSERT

-- G21
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G21001', 'G21', '국립', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G21002', 'G21', '공립', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G21003', 'G21', '사립', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');

-- G22
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G22001', 'G22', 'B10', '서울특별시교육청', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G22002', 'G22', 'C10', '부산광역시교육청', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G22003', 'G22', 'D10', '대구광역시교육청', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G22004', 'G22', 'E10', '인천광역시교육청', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G22005', 'G22', 'F10', '광주광역시교육청', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G22006', 'G22', 'G10', '대전광역시교육청', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G22007', 'G22', 'H10', '울산광역시교육청', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G22008', 'G22', 'I10', '세종특별자치시교육청', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G22009', 'G22', 'J10', '경기도교육청', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G22010', 'G22', 'K10', '강원특별자치도교육청', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G22011', 'G22', 'M10', '충청북도교육청', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G22012', 'G22', 'N10', '충청남도교육청', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G22013', 'G22', 'P10', '전라북도교육청', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G22014', 'G22', 'Q10', '전라남도교육청', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G22015', 'G22', 'R10', '경상북도교육청', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G22016', 'G22', 'S10', '경상남도교육청', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G22017', 'G22', 'T10', '제주특별자치도교육청', 'Y', SYSDATE, 'admin', SYSDATE, 'admin');

-- G23
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G23001', 'G23', '서울특별시', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G23002', 'G23', '부산광역시', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G23003', 'G23', '대구광역시', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G23004', 'G23', '인천광역시', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G23005', 'G23', '광주광역시', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G23006', 'G23', '대전광역시', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G23007', 'G23', '울산광역시', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G23008', 'G23', '세종특별자치시', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G23009', 'G23', '경기도', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G23010', 'G23', '강원특별자치도', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G23011', 'G23', '충청북도', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G23012', 'G23', '충청남도', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G23013', 'G23', '전라북도', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G23014', 'G23', '전라남도', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G23015', 'G23', '경상북도', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G23016', 'G23', '경상남도', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G23017', 'G23', '제주특별자치도', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');

-- G24
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G24001', 'G24', '남', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G24002', 'G24', '여', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G24003', 'G24', '남여공학', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');

-- G25
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G25001', 'G25', '일반고', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G25002', 'G25', '특성화고', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G25003', 'G25', '자율고', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G25004', 'G25', '특목고', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');

-- G26
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G26001', 'G26', '일반계', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');
INSERT INTO COM_CODE (CC_ID, CL_CODE, CC_NAME, CC_ETC, USE_YN, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES ('G26002', 'G26', '전문계', NULL, 'Y', SYSDATE, 'admin', SYSDATE, 'admin');

COMMIT;