--1월 가입자
INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 23, 3, 'userInfo.id_23_sim', 'N',
    TO_DATE('2025-01-12', 'YYYY-MM-DD'), TO_DATE('2025-07-12', 'YYYY-MM-DD'),
    TO_DATE('2025-06-12', 'YYYY-MM-DD'),
    6, TO_DATE('2025-01-12', 'YYYY-MM-DD'), TO_DATE('2025-06-12', 'YYYY-MM-DD')
);

INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 25, 2, 'userInfo.id_25_sim', 'N',
    TO_DATE('2025-02-02', 'YYYY-MM-DD'), TO_DATE('2025-09-02', 'YYYY-MM-DD'),
    TO_DATE('2025-08-02', 'YYYY-MM-DD'),
    6, TO_DATE('2025-02-02', 'YYYY-MM-DD'), TO_DATE('2025-08-02', 'YYYY-MM-DD')
);

INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 26, 1, 'userInfo.id_26_sim', 'N',
    TO_DATE('2025-01-12', 'YYYY-MM-DD'), TO_DATE('2025-04-12', 'YYYY-MM-DD'),
    TO_DATE('2025-03-12', 'YYYY-MM-DD'),
    3, TO_DATE('2025-01-12', 'YYYY-MM-DD'), TO_DATE('2025-03-12', 'YYYY-MM-DD')
);

INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 26, 3, 'userInfo.id_26_sim', 'N',
    TO_DATE('2025-01-12', 'YYYY-MM-DD'), TO_DATE('2025-09-12', 'YYYY-MM-DD'),
    TO_DATE('2025-08-12', 'YYYY-MM-DD'),
    5, TO_DATE('2025-04-12', 'YYYY-MM-DD'), TO_DATE('2025-08-12', 'YYYY-MM-DD')
);

--payment insert 문(1월 가입자)
INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-01-12', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    1, 'imp_500_sim', 'order_23_20250112'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-02-12', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    1, 'imp_501_sim', 'order_23_20250211'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-03-12', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    1, 'imp_502_sim', 'order_23_20250313'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-04-12', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    1, 'imp_503_sim', 'order_23_20250412'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-05-12', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    1, 'imp_504_sim', 'order_23_20250512'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-06-12', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
   1, 'imp_505_sim', 'order_23_20250611'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-02-02', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    2, 'imp_507_sim', 'order_25_20250201'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-03-02', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    2, 'imp_508_sim', 'order_25_20250303'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-04-02', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    2, 'imp_509_sim', 'order_25_20250402'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-05-02', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    2, 'imp_510_sim', 'order_25_20250502'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-06-02', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    2, 'imp_511_sim', 'order_25_20250601'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-07-02', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    2, 'imp_512_sim', 'order_25_20250701'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-01-12', 'YYYY-MM-DD'), 4900,
    3, 3, 3, 3,
    3, 'imp_514_sim', 'order_26_20250112'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-02-12', 'YYYY-MM-DD'), 4900,
    3, 3, 3, 3,
    3, 'imp_515_sim', 'order_26_20250211'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-03-12', 'YYYY-MM-DD'), 4900,
    3, 3, 3, 3,
    3, 'imp_516_sim', 'order_26_20250313'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-04-12', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    4, 'imp_517_sim', 'order_26_20250412'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-05-12', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    4, 'imp_518_sim', 'order_26_20250512'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-06-12', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    4, 'imp_519_sim', 'order_26_20250612'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-07-12', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    4, 'imp_520_sim', 'order_26_20250712'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-12', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    4, 'imp_521_sim', 'order_26_20250812'
);

--2월 가입자
INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 38, 2, 'userInfo.id_38_sim', 'N',
    TO_DATE('2025-02-15', 'YYYY-MM-DD'), TO_DATE('2025-09-15', 'YYYY-MM-DD'),
    TO_DATE('2025-08-15', 'YYYY-MM-DD'),
    7, TO_DATE('2025-02-15', 'YYYY-MM-DD'), TO_DATE('2025-08-15', 'YYYY-MM-DD')
);


INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 39, 2, 'userInfo.id_39_sim', 'N',
    TO_DATE('2025-02-18', 'YYYY-MM-DD'), TO_DATE('2025-04-18', 'YYYY-MM-DD'),
    TO_DATE('2025-03-18', 'YYYY-MM-DD'),
    2, TO_DATE('2025-02-18', 'YYYY-MM-DD'), TO_DATE('2025-03-18', 'YYYY-MM-DD')
);

INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 39, 1, 'userInfo.id_39_sim', 'N',
    TO_DATE('2025-02-18', 'YYYY-MM-DD'), TO_DATE('2025-07-18', 'YYYY-MM-DD'),
    TO_DATE('2025-06-18', 'YYYY-MM-DD'),
    3, TO_DATE('2025-04-18', 'YYYY-MM-DD'), TO_DATE('2025-06-18', 'YYYY-MM-DD')
);


INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 31, 1, 'userInfo.id_31_sim', 'N',
    TO_DATE('2025-06-04', 'YYYY-MM-DD'), TO_DATE('2025-09-04', 'YYYY-MM-DD'),
    TO_DATE('2025-08-04', 'YYYY-MM-DD'),
    3, TO_DATE('2025-06-04', 'YYYY-MM-DD'), TO_DATE('2025-08-04', 'YYYY-MM-DD')
);



INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 40, 3, 'userInfo.id_40_sim', 'N',
    TO_DATE('2025-03-14', 'YYYY-MM-DD'), TO_DATE('2025-05-14', 'YYYY-MM-DD'),
    TO_DATE('2025-04-14', 'YYYY-MM-DD'),
    2, TO_DATE('2025-03-14', 'YYYY-MM-DD'), TO_DATE('2025-04-14', 'YYYY-MM-DD')
);



INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 41, 3, 'userInfo.id_41_sim', 'N',
    TO_DATE('2025-07-02', 'YYYY-MM-DD'), TO_DATE('2025-09-02', 'YYYY-MM-DD'),
    TO_DATE('2025-08-02', 'YYYY-MM-DD'),
    2, TO_DATE('2025-07-02', 'YYYY-MM-DD'), TO_DATE('2025-08-02', 'YYYY-MM-DD')
);

--PAYMENT INSERT(2월)

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-02-15', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    5, 'imp_522_sim', 'order_38_20250215'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-03-15', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    5, 'imp_523_sim', 'order_38_20250315'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-04-15', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    5, 'imp_524_sim', 'order_38_20250415'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-05-15', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    5, 'imp_525_sim', 'order_38_20250515'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-06-15', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    5, 'imp_526_sim', 'order_38_20250615'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-07-15', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    5, 'imp_527_sim', 'order_38_20250715'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-15', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    5, 'imp_528_sim', 'order_38_20250815'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-02-18', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    6, 'imp_529_sim', 'order_39_20250218'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-03-18', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    6, 'imp_530_sim', 'order_39_20250318'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-04-18', 'YYYY-MM-DD'), 4900,
    3, 3, 3, 3,
    7, 'imp_531_sim', 'order_39_20250418'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-05-18', 'YYYY-MM-DD'), 4900,
    3, 3, 3, 3,
    7, 'imp_532_sim', 'order_39_20250518'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-06-18', 'YYYY-MM-DD'), 4900,
    3, 3, 3, 3,
    7, 'imp_533_sim', 'order_39_20250618'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-06-04', 'YYYY-MM-DD'), 4900,
    3, 3, 3, 3,
    8, 'imp_534_sim', 'order_31_20250604'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-07-04', 'YYYY-MM-DD'), 4900,
    3, 3, 3, 3,
    8, 'imp_535_sim', 'order_31_20250704'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-04', 'YYYY-MM-DD'), 13900,
    3, 3, 3, 3,
    8, 'imp_536_sim', 'order_31_20250804'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-03-14', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    9, 'imp_537_sim', 'order_40_20250314'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-04-14', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    9, 'imp_538_sim', 'order_40_20250414'
);



INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-07-02', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    10, 'imp_539_sim', 'order_41_20250702'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-02', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    10, 'imp_540_sim', 'order_41_20250802'
);


--3월 가입자


INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 37, 2, 'userInfo.id_37_sim', 'N',
    TO_DATE('2025-04-12', 'YYYY-MM-DD'), TO_DATE('2025-08-12', 'YYYY-MM-DD'),
    TO_DATE('2025-07-12', 'YYYY-MM-DD'),
    4, TO_DATE('2025-04-12', 'YYYY-MM-DD'), TO_DATE('2025-07-12', 'YYYY-MM-DD')
);


INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 35, 3, 'userInfo.id_35_sim', 'N',
    TO_DATE('2025-06-12', 'YYYY-MM-DD'), TO_DATE('2025-07-12', 'YYYY-MM-DD'),
    TO_DATE('2025-06-12', 'YYYY-MM-DD'),
    1, TO_DATE('2025-06-12', 'YYYY-MM-DD'), TO_DATE('2025-06-12', 'YYYY-MM-DD')
);


INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 32, 2, 'userInfo.id_32_sim', 'N',
    TO_DATE('2025-03-15', 'YYYY-MM-DD'), TO_DATE('2025-08-12', 'YYYY-MM-DD'),
    TO_DATE('2025-07-15', 'YYYY-MM-DD'),
    5, TO_DATE('2025-03-12', 'YYYY-MM-DD'), TO_DATE('2025-07-12', 'YYYY-MM-DD')
);


INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 34, 3, 'userInfo.id_34_sim', 'N',
    TO_DATE('2025-03-18', 'YYYY-MM-DD'), TO_DATE('2025-07-18', 'YYYY-MM-DD'),
    TO_DATE('2025-06-18', 'YYYY-MM-DD'),
    4, TO_DATE('2025-03-18', 'YYYY-MM-DD'), TO_DATE('2025-06-18', 'YYYY-MM-DD')
);

--PAYMENT INSERT(3월)


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-04-12', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    11, 'imp_541_sim', 'order_37_20250412'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-05-12', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    11, 'imp_542_sim', 'order_37_20250512'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-06-12', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    11, 'imp_543_sim', 'order_37_20250612'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-07-12', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    11, 'imp_544_sim', 'order_37_20250712'
);



INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-06-12', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    12, 'imp_545_sim', 'order_37_20250612'
);



INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-03-15', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    13, 'imp_546_sim', 'order_32_20250315'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-04-15', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    13, 'imp_547_sim', 'order_32_20250415'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-05-15', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    13, 'imp_548_sim', 'order_32_20250515'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-06-15', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    13, 'imp_549_sim', 'order_32_20250615'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-07-15', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    13, 'imp_550_sim', 'order_32_20250715'
);



INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-03-18', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    14, 'imp_551_sim', 'order_34_20250318'
);



INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-04-18', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    14, 'imp_552_sim', 'order_34_20250418'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-05-18', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    14, 'imp_553_sim', 'order_34_20250518'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-06-18', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    14, 'imp_554_sim', 'order_34_20250618'
);


--4월 가입자

INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 30, 1, 'userInfo.id_30_sim', 'N',
    TO_DATE('2025-04-18', 'YYYY-MM-DD'), TO_DATE('2025-09-18', 'YYYY-MM-DD'),
    TO_DATE('2025-08-18', 'YYYY-MM-DD'),
    5, TO_DATE('2025-04-18', 'YYYY-MM-DD'), TO_DATE('2025-08-18', 'YYYY-MM-DD')
);


INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 49, 3, 'userInfo.id_49_sim', 'N',
    TO_DATE('2025-04-13', 'YYYY-MM-DD'), TO_DATE('2025-06-18', 'YYYY-MM-DD'),
    TO_DATE('2025-05-13', 'YYYY-MM-DD'),
    2, TO_DATE('2025-04-13', 'YYYY-MM-DD'), TO_DATE('2025-05-13', 'YYYY-MM-DD')
);

INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 29, 2, 'userInfo.id_29_sim', 'N',
    TO_DATE('2025-04-13', 'YYYY-MM-DD'), TO_DATE('2025-09-18', 'YYYY-MM-DD'),
    TO_DATE('2025-08-13', 'YYYY-MM-DD'),
    5, TO_DATE('2025-04-13', 'YYYY-MM-DD'), TO_DATE('2025-08-13', 'YYYY-MM-DD')
);

--PAYMENT(4월)



INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-04-18', 'YYYY-MM-DD'), 4900,
    3, 3, 3, 3,
    15, 'imp_555_sim', 'order_30_20250318'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-05-18', 'YYYY-MM-DD'), 4900,
    3, 3, 3, 3,
    15, 'imp_556_sim', 'order_30_20250418'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-06-18', 'YYYY-MM-DD'), 4900,
    3, 3, 3, 3,
    15, 'imp_557_sim', 'order_30_20250518'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-07-18', 'YYYY-MM-DD'), 4900,
    3, 3, 3, 3,
    15, 'imp_558_sim', 'order_30_20250618'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-18', 'YYYY-MM-DD'), 4900,
    3, 3, 3, 3,
    15, 'imp_559_sim', 'order_30_20250718'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-04-13', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    16, 'imp_560_sim', 'order_49_20250413'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-05-13', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    16, 'imp_561_sim', 'order_49_20250513'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-04-13', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    17, 'imp_562_sim', 'order_29_20250413'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-05-13', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    17, 'imp_563_sim', 'order_29_20250513'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-06-13', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    17, 'imp_564_sim', 'order_29_20250613'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-07-13', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    17, 'imp_565_sim', 'order_29_20250713'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-13', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    17, 'imp_566_sim', 'order_29_20250813'
);

--5월 가입자

INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 28, 2, 'userInfo.id_28_sim', 'N',
    TO_DATE('2025-05-18', 'YYYY-MM-DD'), TO_DATE('2025-09-18', 'YYYY-MM-DD'),
    TO_DATE('2025-08-18', 'YYYY-MM-DD'),
    4, TO_DATE('2025-05-18', 'YYYY-MM-DD'), TO_DATE('2025-08-18', 'YYYY-MM-DD')
);



INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 47, 2, 'userInfo.id_47_sim', 'N',
    TO_DATE('2025-05-18', 'YYYY-MM-DD'), TO_DATE('2025-07-18', 'YYYY-MM-DD'),
    TO_DATE('2025-06-18', 'YYYY-MM-DD'),
    2, TO_DATE('2025-05-18', 'YYYY-MM-DD'), TO_DATE('2025-06-18', 'YYYY-MM-DD')
);

INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 46, 1, 'userInfo.id_46_sim', 'N',
    TO_DATE('2025-06-08', 'YYYY-MM-DD'), TO_DATE('2025-09-08', 'YYYY-MM-DD'),
    TO_DATE('2025-08-08', 'YYYY-MM-DD'),
    3, TO_DATE('2025-06-08', 'YYYY-MM-DD'), TO_DATE('2025-08-08', 'YYYY-MM-DD')
);

INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 42, 2, 'userInfo.id_42_sim', 'N',
    TO_DATE('2025-07-10', 'YYYY-MM-DD'), TO_DATE('2025-09-10', 'YYYY-MM-DD'),
    TO_DATE('2025-08-10', 'YYYY-MM-DD'),
    2, TO_DATE('2025-07-10', 'YYYY-MM-DD'), TO_DATE('2025-08-10', 'YYYY-MM-DD')
);


INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 45, 3, 'userInfo.id_45_sim', 'N',
    TO_DATE('2025-05-19', 'YYYY-MM-DD'), TO_DATE('2025-09-19', 'YYYY-MM-DD'),
    TO_DATE('2025-08-19', 'YYYY-MM-DD'),
    4, TO_DATE('2025-05-19', 'YYYY-MM-DD'), TO_DATE('2025-08-19', 'YYYY-MM-DD')
);


--PAYMENT(5월)

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-05-18', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    18, 'imp_567_sim', 'order_28_20250518'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-06-18', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    18, 'imp_568_sim', 'order_28_20250618'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-07-18', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    18, 'imp_569_sim', 'order_28_20250718'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-18', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    18, 'imp_570_sim', 'order_28_20250818'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-05-18', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    19, 'imp_570_sim', 'order_47_20250518'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-06-18', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    19, 'imp_571_sim', 'order_47_20250618'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-06-08', 'YYYY-MM-DD'), 4900,
    3, 3, 3, 3,
    20, 'imp_572_sim', 'order_46_20250608'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-07-08', 'YYYY-MM-DD'), 4900,
    3, 3, 3, 3,
    20, 'imp_573_sim', 'order_46_20250708'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-08', 'YYYY-MM-DD'), 4900,
    3, 3, 3, 3,
    20, 'imp_574_sim', 'order_46_20250808'
);



INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-07-10', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    21, 'imp_575_sim', 'order_42_20250710'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-10', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    21, 'imp_576_sim', 'order_42_20250810'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-05-19', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    22, 'imp_577_sim', 'order_45_20250819'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-06-19', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    22, 'imp_578_sim', 'order_45_20250619'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-07-19', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    22, 'imp_578_sim', 'order_45_20250719'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-19', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    22, 'imp_579_sim', 'order_45_20250819'
);


--6월 가입자

INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 10, 2, 'userInfo.id_10_sim', 'N',
    TO_DATE('2025-06-15', 'YYYY-MM-DD'), TO_DATE('2025-09-15', 'YYYY-MM-DD'),
    TO_DATE('2025-08-15', 'YYYY-MM-DD'),
    3, TO_DATE('2025-06-15', 'YYYY-MM-DD'), TO_DATE('2025-08-15', 'YYYY-MM-DD')
);


INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 27, 3, 'userInfo.id_27_sim', 'N',
    TO_DATE('2025-06-15', 'YYYY-MM-DD'), TO_DATE('2025-07-15', 'YYYY-MM-DD'),
    TO_DATE('2025-06-15', 'YYYY-MM-DD'),
    1, TO_DATE('2025-06-15', 'YYYY-MM-DD'), TO_DATE('2025-06-15', 'YYYY-MM-DD')
);



--PAYMENT(6월)


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-06-15', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    23, 'imp_580_sim', 'order_10_20250615'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-07-15', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    23, 'imp_581_sim', 'order_10_20250715'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-15', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    23, 'imp_582_sim', 'order_10_20250815'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-06-15', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    24, 'imp_583_sim', 'order_27_20250615'
);


--7월 가입자

INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 24, 1, 'userInfo.id_24_sim', 'N',
    TO_DATE('2025-07-15', 'YYYY-MM-DD'), TO_DATE('2025-08-15', 'YYYY-MM-DD'),
    TO_DATE('2025-08-15', 'YYYY-MM-DD'),
    1, TO_DATE('2025-07-15', 'YYYY-MM-DD'), TO_DATE('2025-07-15', 'YYYY-MM-DD')
);

INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 9, 2, 'userInfo.id_9_sim', 'N',
    TO_DATE('2025-07-25', 'YYYY-MM-DD'), TO_DATE('2025-08-25', 'YYYY-MM-DD'),
    TO_DATE('2025-07-25', 'YYYY-MM-DD'),
    1, TO_DATE('2025-07-25', 'YYYY-MM-DD'), TO_DATE('2025-07-25', 'YYYY-MM-DD')
);


INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 1, 1, 'userInfo.id_1_sim', 'N',
    TO_DATE('2025-07-25', 'YYYY-MM-DD'), TO_DATE('2025-09-25', 'YYYY-MM-DD'),
    TO_DATE('2025-08-25', 'YYYY-MM-DD'),
    2, TO_DATE('2025-08-25', 'YYYY-MM-DD'), TO_DATE('2025-08-25', 'YYYY-MM-DD')
);


INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 2, 1, 'userInfo.id_2_sim', 'N',
    TO_DATE('2025-07-25', 'YYYY-MM-DD'), TO_DATE('2025-09-25', 'YYYY-MM-DD'),
    TO_DATE('2025-08-25', 'YYYY-MM-DD'),
    2, TO_DATE('2025-08-25', 'YYYY-MM-DD'), TO_DATE('2025-08-25', 'YYYY-MM-DD')
);

INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 3, 3, 'userInfo.id_3_sim', 'N',
    TO_DATE('2025-07-26', 'YYYY-MM-DD'), TO_DATE('2025-08-26', 'YYYY-MM-DD'),
    TO_DATE('2025-07-26', 'YYYY-MM-DD'),
    1, TO_DATE('2025-07-26', 'YYYY-MM-DD'), TO_DATE('2025-07-26', 'YYYY-MM-DD')
);

INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 4, 2, 'userInfo.id_4_sim', 'N',
    TO_DATE('2025-07-26', 'YYYY-MM-DD'), TO_DATE('2025-09-26', 'YYYY-MM-DD'),
    TO_DATE('2025-08-26', 'YYYY-MM-DD'),
    2, TO_DATE('2025-07-26', 'YYYY-MM-DD'), TO_DATE('2025-08-26', 'YYYY-MM-DD')
);


INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 5, 2, 'userInfo.id_5_sim', 'N',
    TO_DATE('2025-08-10', 'YYYY-MM-DD'), TO_DATE('2025-09-10', 'YYYY-MM-DD'),
    TO_DATE('2025-08-10', 'YYYY-MM-DD'),
    1, TO_DATE('2025-08-10', 'YYYY-MM-DD'), TO_DATE('2025-08-10', 'YYYY-MM-DD')
);

INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 6, 2, 'userInfo.id_6_sim', 'N',
    TO_DATE('2025-07-10', 'YYYY-MM-DD'), TO_DATE('2025-09-10', 'YYYY-MM-DD'),
    TO_DATE('2025-08-10', 'YYYY-MM-DD'),
    2, TO_DATE('2025-07-10', 'YYYY-MM-DD'), TO_DATE('2025-08-10', 'YYYY-MM-DD')
);


INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 8, 2, 'userInfo.id_1_sim', 'N',
    TO_DATE('2025-07-10', 'YYYY-MM-DD'), TO_DATE('2025-09-10', 'YYYY-MM-DD'),
    TO_DATE('2025-08-10', 'YYYY-MM-DD'),
    2, TO_DATE('2025-07-10', 'YYYY-MM-DD'), TO_DATE('2025-08-10', 'YYYY-MM-DD')
);

--PAYMENT(7월)


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-07-15', 'YYYY-MM-DD'), 4900,
    3, 3, 3, 3,
    25, 'imp_584_sim', 'order_27_20250715'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-07-25', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    26, 'imp_585_sim', 'order_9_20250725'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-07-25', 'YYYY-MM-DD'), 4900,
    3, 3, 3, 3,
    27, 'imp_586_sim', 'order_1_20250725'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-07-25', 'YYYY-MM-DD'), 4900,
    3, 3, 3, 3,
    28, 'imp_587_sim', 'order_2_20250725'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-07-26', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    29, 'imp_588_sim', 'order_3_20250726'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-07-26', 'YYYY-MM-DD'), 9900,
    8, 8, 8, 8,
    30, 'imp_589_sim', 'order_4_20250726'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-26', 'YYYY-MM-DD'), 9900,
    8, 8, 8, 8,
    31, 'imp_590_sim', 'order_4_20250826'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-25', 'YYYY-MM-DD'), 4900,
    3, 3, 3, 3,
    27, 'imp_591_sim', 'order_1_20250825'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-25', 'YYYY-MM-DD'), 4900,
    3, 3, 3, 3,
    28, 'imp_592_sim', 'order_2_20250825'
);



INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-10', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    31, 'imp_593_sim', 'order_5_20250810'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-10', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    32, 'imp_594_sim', 'order_6_20250810'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-10', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    33, 'imp_595_sim', 'order_8_20250810'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-07-10', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    32, 'imp_597_sim', 'order_6_20250710'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-07-10', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    33, 'imp_598_sim', 'order_8_20250710'
);

--8월 가입자

INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 12, 1, 'userInfo.id_12_sim', 'N',
    TO_DATE('2025-08-10', 'YYYY-MM-DD'), TO_DATE('2025-09-10', 'YYYY-MM-DD'),
    TO_DATE('2025-08-10', 'YYYY-MM-DD'),
    1, TO_DATE('2025-08-10', 'YYYY-MM-DD'), TO_DATE('2025-08-10', 'YYYY-MM-DD')
);


INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 11, 2, 'userInfo.id_11_sim', 'N',
    TO_DATE('2025-08-10', 'YYYY-MM-DD'), TO_DATE('2025-09-10', 'YYYY-MM-DD'),
    TO_DATE('2025-08-10', 'YYYY-MM-DD'),
    1, TO_DATE('2025-08-10', 'YYYY-MM-DD'), TO_DATE('2025-08-10', 'YYYY-MM-DD')
);

INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 14, 2, 'userInfo.id_14_sim', 'N',
    TO_DATE('2025-08-10', 'YYYY-MM-DD'), TO_DATE('2025-09-10', 'YYYY-MM-DD'),
    TO_DATE('2025-08-10', 'YYYY-MM-DD'),
    1, TO_DATE('2025-08-10', 'YYYY-MM-DD'), TO_DATE('2025-08-10', 'YYYY-MM-DD')
);


INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 15, 2, 'userInfo.id_15_sim', 'N',
    TO_DATE('2025-08-11', 'YYYY-MM-DD'), TO_DATE('2025-09-11', 'YYYY-MM-DD'),
    TO_DATE('2025-08-11', 'YYYY-MM-DD'),
    1, TO_DATE('2025-08-11', 'YYYY-MM-DD'), TO_DATE('2025-08-11', 'YYYY-MM-DD')
);


INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 13, 2, 'userInfo.id_13_sim', 'N',
    TO_DATE('2025-08-11', 'YYYY-MM-DD'), TO_DATE('2025-09-11', 'YYYY-MM-DD'),
    TO_DATE('2025-08-11', 'YYYY-MM-DD'),
    1, TO_DATE('2025-08-11', 'YYYY-MM-DD'), TO_DATE('2025-08-11', 'YYYY-MM-DD')
);


INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 16, 1, 'userInfo.id_13_sim', 'N',
    TO_DATE('2025-08-11', 'YYYY-MM-DD'), TO_DATE('2025-09-11', 'YYYY-MM-DD'),
    TO_DATE('2025-08-11', 'YYYY-MM-DD'),
    1, TO_DATE('2025-08-11', 'YYYY-MM-DD'), TO_DATE('2025-08-11', 'YYYY-MM-DD')
);

INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 17, 3, 'userInfo.id_17_sim', 'N',
    TO_DATE('2025-08-15', 'YYYY-MM-DD'), TO_DATE('2025-09-11', 'YYYY-MM-DD'),
    TO_DATE('2025-08-15', 'YYYY-MM-DD'),
    1, TO_DATE('2025-08-15', 'YYYY-MM-DD'), TO_DATE('2025-08-15', 'YYYY-MM-DD')
);


INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 18, 3, 'userInfo.id_18_sim', 'N',
    TO_DATE('2025-08-15', 'YYYY-MM-DD'), TO_DATE('2025-09-11', 'YYYY-MM-DD'),
    TO_DATE('2025-08-15', 'YYYY-MM-DD'),
    1, TO_DATE('2025-08-15', 'YYYY-MM-DD'), TO_DATE('2025-08-15', 'YYYY-MM-DD')
);


INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 22, 2, 'userInfo.id_18_sim', 'N',
    TO_DATE('2025-08-15', 'YYYY-MM-DD'), TO_DATE('2025-09-11', 'YYYY-MM-DD'),
    TO_DATE('2025-08-15', 'YYYY-MM-DD'),
    1, TO_DATE('2025-08-15', 'YYYY-MM-DD'), TO_DATE('2025-08-15', 'YYYY-MM-DD')
);


INSERT INTO MEMBER_SUBSCRIPTION (
    MS_ID, MEM_ID, SUB_ID, CUSTOMER_UID, SUB_STATUS,
    SUB_START_DT, SUB_END_DT, LAST_PAY_DT,
    RECUR_PAY_CNT, CREATED_DT, UPDATED_DT
) VALUES (
    MEMBER_SUBSCRIPTION_SEQ.NEXTVAL, 26, 1, 'userInfo.id_26_sim1', 'N',
    TO_DATE('2025-06-12', 'YYYY-MM-DD'), TO_DATE('2025-07-12', 'YYYY-MM-DD'),
    TO_DATE('2025-06-12', 'YYYY-MM-DD'),
    3, TO_DATE('2025-06-12', 'YYYY-MM-DD'), TO_DATE('2025-06-12', 'YYYY-MM-DD')
);

--PAYMENT(8월)


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-10', 'YYYY-MM-DD'), 4900,
    3, 3, 3, 3,
    34, 'imp_596_sim', 'order_12_20250810'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-10', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    35, 'imp_599_sim', 'order_11_20250710'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-10', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    36, 'imp_600_sim', 'order_14_20250710'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-11', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    37, 'imp_601_sim', 'order_15_20250711'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-11', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    38, 'imp_602_sim', 'order_13_20250711'
);

INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-11', 'YYYY-MM-DD'), 4900,
    3, 3, 3, 3,
    39, 'imp_603_sim', 'order_16_20250711'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-15', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    40, 'imp_604_sim', 'order_15_20250711'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-15', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    41, 'imp_605_sim', 'order_18_20250815'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-08-15', 'YYYY-MM-DD'), 9900,
    6, 6, 6, 6,
    42, 'imp_605_sim', 'order_22_20250815'
);


INSERT INTO PAYMENT (
    PAY_ID, PAY_DATE, PAY_AMOUNT, PAY_RESUME_CNT, PAY_COVER_CNT,
    PAY_CONSULT_CNT, PAY_MOCK_CNT, MS_ID, IMP_UID, MERCHANT_UID
) VALUES (
    PAYMENT_SEQ.NEXTVAL, TO_DATE('2025-06-12', 'YYYY-MM-DD'), 13900,
    8, 8, 8, 8,
    43, 'imp_606_sim', 'order_26_20250612'
);

COMMIT;
ROLLBACK;