TRUNCATE TABLE NEW_SUB_MEMBERS;

-- 2월
INSERT INTO NEW_SUB_MEMBERS (MONTH_KEY, MEM_ID) VALUES ('02', 65);
INSERT INTO NEW_SUB_MEMBERS (MONTH_KEY, MEM_ID) VALUES ('02', 63);
INSERT INTO NEW_SUB_MEMBERS (MONTH_KEY, MEM_ID) VALUES ('02', 61);
INSERT INTO NEW_SUB_MEMBERS (MONTH_KEY, MEM_ID) VALUES ('02', 50);

-- 4월
INSERT INTO NEW_SUB_MEMBERS VALUES ('04', 68);
INSERT INTO NEW_SUB_MEMBERS VALUES ('04', 70);
INSERT INTO NEW_SUB_MEMBERS VALUES ('04', 64);
INSERT INTO NEW_SUB_MEMBERS VALUES ('04', 66);
INSERT INTO NEW_SUB_MEMBERS VALUES ('04', 72);
INSERT INTO NEW_SUB_MEMBERS VALUES ('04', 60);

-- 5월
INSERT INTO NEW_SUB_MEMBERS VALUES ('05', 58);
INSERT INTO NEW_SUB_MEMBERS VALUES ('05', 57);
INSERT INTO NEW_SUB_MEMBERS VALUES ('05', 59);

-- 7월
INSERT INTO NEW_SUB_MEMBERS VALUES ('07', 78);
INSERT INTO NEW_SUB_MEMBERS VALUES ('07', 79);
INSERT INTO NEW_SUB_MEMBERS VALUES ('07', 77);
INSERT INTO NEW_SUB_MEMBERS VALUES ('07', 76);
INSERT INTO NEW_SUB_MEMBERS VALUES ('07', 75);
INSERT INTO NEW_SUB_MEMBERS VALUES ('07', 74);
INSERT INTO NEW_SUB_MEMBERS VALUES ('07', 73);
INSERT INTO NEW_SUB_MEMBERS VALUES ('07', 62);
INSERT INTO NEW_SUB_MEMBERS VALUES ('07', 80);
INSERT INTO NEW_SUB_MEMBERS VALUES ('07', 56);

-- 8월
INSERT INTO NEW_SUB_MEMBERS VALUES ('08', 51);
INSERT INTO NEW_SUB_MEMBERS VALUES ('08', 54);
INSERT INTO NEW_SUB_MEMBERS VALUES ('08', 52);
INSERT INTO NEW_SUB_MEMBERS VALUES ('08', 53);
INSERT INTO NEW_SUB_MEMBERS VALUES ('08', 55);
INSERT INTO NEW_SUB_MEMBERS VALUES ('08', 83);
INSERT INTO NEW_SUB_MEMBERS VALUES ('08', 81);
INSERT INTO NEW_SUB_MEMBERS VALUES ('08', 82);
INSERT INTO NEW_SUB_MEMBERS VALUES ('08', 84);
INSERT INTO NEW_SUB_MEMBERS VALUES ('08', 85);
INSERT INTO NEW_SUB_MEMBERS VALUES ('08', 86);

COMMIT;

select *
from NEW_SUB_MEMBERS


DELETE FROM PAYMENT p
WHERE p.MS_ID IN (
  SELECT ms_id FROM MEMBER_SUBSCRIPTION
  WHERE CUSTOMER_UID LIKE 'userInfo.id_%_sim_new'
);
DELETE FROM MEMBER_SUBSCRIPTION
WHERE CUSTOMER_UID LIKE 'userInfo.id_%_sim_new';
COMMIT;

-- 신규 멤버 입력용
CREATE GLOBAL TEMPORARY TABLE NEW_SUB_MEMBERS (
  MONTH_KEY CHAR(2),   -- '02','04','05','07','08' 등
  MEM_ID    NUMBER
) ON COMMIT PRESERVE ROWS;

-- 이번에 만들 신규 구독 버퍼 (구독/결제 공통으로 사용)
CREATE GLOBAL TEMPORARY TABLE NEW_SUBS_BUF (
  MS_ID         NUMBER,
  MEM_ID        NUMBER,
  SUB_ID        NUMBER,
  START_DT      DATE,
  END_DT        DATE,
  LAST_PAY_DT   DATE,
  RECUR_CNT     NUMBER,
  CUSTOMER_UID  VARCHAR2(50)
) ON COMMIT PRESERVE ROWS;

