--상품별 월별 결제 구독수
SELECT
  TO_CHAR(P.PAY_DATE, 'YYYY.MM') AS MONTH,
  S.SUB_NAME,
  COUNT(*) AS NEW_SUBSCRIBER_COUNT
FROM MEMBER_SUBSCRIPTION MS
JOIN PAYMENT P ON P.MS_ID = MS.MS_ID
JOIN SUBSCRIBE S ON S.SUB_ID= MS.SUB_ID
GROUP BY TO_CHAR(P.PAY_DATE, 'YYYY.MM'),
      S.SUB_NAME
ORDER BY MONTH;

---- 월별 총구독자 수
SELECT
  TO_CHAR(P.PAY_DATE, 'YYYY.MM') AS MONTH,
  COUNT(*) AS NEW_SUBSCRIBER_COUNT
FROM MEMBER_SUBSCRIPTION MS
JOIN PAYMENT P ON P.MS_ID = MS.MS_ID
GROUP BY TO_CHAR(P.PAY_DATE, 'YYYY.MM')
ORDER BY MONTH;


-- 월별 총 결제금
SELECT
  TO_CHAR(PAY_DATE, 'YYYY.MM') AS MONTH,
  SUM(PAY_AMOUNT) AS TOTAL_AMOUNT
FROM
  PAYMENT
GROUP BY
  TO_CHAR(PAY_DATE, 'YYYY.MM')
ORDER BY
  MONTH;
  
  
-- 월별 신규 구독자 수
SELECT
  TO_CHAR(P.PAY_DATE, 'YYYY.MM') AS MONTH,
  COUNT(*) AS NEW_PAYING_USERS
FROM PAYMENT P
WHERE P.PAY_DATE = (
  SELECT MIN(P2.PAY_DATE)
  FROM PAYMENT P2
  JOIN MEMBER_SUBSCRIPTION MS2 ON P2.MS_ID = MS2.MS_ID
  WHERE MS2.MEM_ID = (
    SELECT MS3.MEM_ID
    FROM MEMBER_SUBSCRIPTION MS3
    WHERE MS3.MS_ID = P.MS_ID
  )
)
GROUP BY TO_CHAR(P.PAY_DATE, 'YYYY.MM')
ORDER BY MONTH;

--월별 신규 가입결제
SELECT
  TO_CHAR(P.PAY_DATE, 'YYYY.MM') AS MONTH,
  SUM(P.PAY_AMOUNT) AS NEW_SUBSCRIB_PAY
FROM PAYMENT P
WHERE P.PAY_DATE = (
  SELECT MIN(P2.PAY_DATE)
  FROM PAYMENT P2
  JOIN MEMBER_SUBSCRIPTION MS2 ON P2.MS_ID = MS2.MS_ID
  WHERE MS2.MEM_ID = (
    SELECT MS3.MEM_ID
    FROM MEMBER_SUBSCRIPTION MS3
    WHERE MS3.MS_ID = P.MS_ID
  )
)
GROUP BY TO_CHAR(P.PAY_DATE, 'YYYY.MM')
ORDER BY MONTH;
  

--월별 취소
SELECT
  TO_CHAR(MS.SUB_END_DT, 'YYYY.MM') AS MONTH,
  COUNT(*) AS CANCEL_COUNT
FROM MEMBER_SUBSCRIPTION MS
WHERE SUB_STATUS = 'N'
AND NOT EXISTS(
    SELECT 1
    FROM MEMBER_SUBSCRIPTION MS2
    WHERE MS.CUSTOMER_UID = MS2.CUSTOMER_UID
    AND MS2.SUB_STATUS = 'Y'
    AND MS2.SUB_START_DT = MS.SUB_START_DT
    AND MS2.MS_ID>MS.MS_ID
)
GROUP BY TO_CHAR(MS.SUB_END_DT, 'YYYY.MM')
ORDER BY MONTH;



--월별 취소 금액
SELECT
  TO_CHAR(MS.SUB_END_DT, 'YYYY.MM') AS MONTH,
  SUM(S.SUB_PRICE) AS CANCEL_AMOUNT
FROM MEMBER_SUBSCRIPTION MS
JOIN SUBSCRIBE S ON S.SUB_ID = MS.SUB_ID
WHERE SUB_STATUS = 'N'
AND NOT EXISTS(
    SELECT 1
    FROM MEMBER_SUBSCRIPTION MS2
    WHERE MS.CUSTOMER_UID = MS2.CUSTOMER_UID
    AND MS2.SUB_STATUS = 'Y'
    AND MS2.SUB_START_DT = MS.SUB_START_DT
    AND MS2.MS_ID>MS.MS_ID
)
GROUP BY TO_CHAR(MS.SUB_END_DT, 'YYYY.MM')
ORDER BY MONTH;

--월별 변화
SELECT
  TO_CHAR(MS.SUB_END_DT, 'YYYY.MM') AS MONTH,
  COUNT(*) AS CANCEL_COUNT
FROM MEMBER_SUBSCRIPTION MS
WHERE SUB_STATUS = 'N'
AND EXISTS(
    SELECT 1
    FROM MEMBER_SUBSCRIPTION MS2
    WHERE MS.CUSTOMER_UID = MS2.CUSTOMER_UID
    AND MS2.SUB_STATUS = 'Y'
    AND MS2.SUB_START_DT = MS.SUB_START_DT
    AND MS2.MS_ID>MS.MS_ID
)
GROUP BY TO_CHAR(MS.SUB_END_DT, 'YYYY.MM')
ORDER BY MONTH;

--월별 업그레이드 수
SELECT
  TO_CHAR(MS.SUB_END_DT, 'YYYY.MM') AS MONTH,
  COUNT(*) AS UPGRAD_COUNT
FROM MEMBER_SUBSCRIPTION MS
JOIN SUBSCRIBE S ON S.SUB_ID = MS.SUB_ID
WHERE SUB_STATUS = 'N'
AND EXISTS(
    SELECT 1
    FROM MEMBER_SUBSCRIPTION MS2
    JOIN SUBSCRIBE S2 ON S2.SUB_ID = MS2.SUB_ID
    WHERE MS.CUSTOMER_UID = MS2.CUSTOMER_UID
    AND MS2.SUB_STATUS = 'Y'
    AND MS2.SUB_START_DT = MS.SUB_START_DT
    AND MS2.MS_ID>MS.MS_ID
    AND S2.SUB_PRICE>S.SUB_PRICE
)
GROUP BY TO_CHAR(MS.SUB_END_DT, 'YYYY.MM')
ORDER BY MONTH;

--월별 업그레이드 결제금액
SELECT
  TO_CHAR(MS.SUB_END_DT, 'YYYY.MM') AS MONTH,
  SUM(S2.SUB_PRICE - S.SUB_PRICE) AS UPGRAD_COUNT
FROM MEMBER_SUBSCRIPTION MS
JOIN SUBSCRIBE S ON S.SUB_ID = MS.SUB_ID
WHERE SUB_STATUS = 'N'
AND EXISTS(
    SELECT 1
    FROM MEMBER_SUBSCRIPTION MS2
    JOIN SUBSCRIBE S2 ON S2.SUB_ID = MS2.SUB_ID
    WHERE MS.CUSTOMER_UID = MS2.CUSTOMER_UID
    AND MS2.SUB_STATUS = 'Y'
    AND MS2.SUB_START_DT = MS.SUB_START_DT
    AND MS2.MS_ID>MS.MS_ID
    AND S2.SUB_PRICE>S.SUB_PRICE
)
GROUP BY TO_CHAR(MS.SUB_END_DT, 'YYYY.MM')
ORDER BY MONTH;

--월별 다운그레이드 수
SELECT
  TO_CHAR(MS.SUB_END_DT, 'YYYY.MM') AS MONTH,
  COUNT(*) AS DOWNGRAD_COUNT
FROM MEMBER_SUBSCRIPTION MS
JOIN SUBSCRIBE S ON S.SUB_ID = MS.SUB_ID
WHERE SUB_STATUS = 'N'
AND EXISTS(
    SELECT 1
    FROM MEMBER_SUBSCRIPTION MS2
    JOIN SUBSCRIBE S2 ON S2.SUB_ID = MS2.SUB_ID
    WHERE MS.CUSTOMER_UID = MS2.CUSTOMER_UID
    AND MS2.SUB_STATUS = 'Y'
    AND MS2.SUB_START_DT = MS.SUB_START_DT
    AND MS2.MS_ID>MS.MS_ID
    AND S2.SUB_PRICE<S.SUB_PRICE
)
GROUP BY TO_CHAR(MS.SUB_END_DT, 'YYYY.MM')
ORDER BY MONTH;

--월별 다운레이드 결제금액
SELECT
  TO_CHAR(MS.SUB_END_DT, 'YYYY.MM') AS MONTH,
  SUM(S.SUB_PRICE) AS DOWNGRAD_COUNT
FROM MEMBER_SUBSCRIPTION MS
JOIN SUBSCRIBE S ON S.SUB_ID = MS.SUB_ID
WHERE SUB_STATUS = 'N'
AND EXISTS(
    SELECT 1
    FROM MEMBER_SUBSCRIPTION MS2
    JOIN SUBSCRIBE S2 ON S2.SUB_ID = MS2.SUB_ID
    WHERE MS.CUSTOMER_UID = MS2.CUSTOMER_UID
    AND MS2.SUB_STATUS = 'Y'
    AND MS2.SUB_START_DT = MS.SUB_START_DT
    AND MS2.MS_ID>MS.MS_ID
    AND S2.SUB_PRICE<S.SUB_PRICE
)
GROUP BY TO_CHAR(MS.SUB_END_DT, 'YYYY.MM')
ORDER BY MONTH;